### ISSUE TITLE
Ignore preamble

### ISSUE THREAD

**Issue by rwmitchell** [mogelbrod/vim-jsonpath#10]
This is certainly of limited practicality.  I've come up with a method of embedding JSON data in a text file.  I can either just execute file and have the JSON contents displayed or add json.notation to specify just those records.  My files start with:

```sh
#!/bin/sh
SL=$(egrep '^\s*{$|^\s*},*$|^\s*],*$|^\,*$|\"\s*:|^\s*\".*\",*\s*$' $0 | sed '/^\s*$/d')

if   [ "$1" == "test" ]; then
  printf "$SL\n" | js_parser | num
elif [ "$1" == "raw" ]; then
  printf "$SL\n" | js_parser
elif [ "$1" == "keys" ]; then
  printf "$SL\n" | js_parser | jq -r $1//empty
else
  printf "$SL\n" | js_parser | jq -r .$1//empty
fi

exit 0;

{
```

js_parser is my own, it filters out the non-json stuff before writing it to jq to do the json parsing.

After deleting the lines above (down to before '{'), the plugin worked great.

**Comment by mogelbrod** [comment]
Hi @rwmitchell!

Have I understood you correctly in that you wish to be able to configure the plugin to ignore everything before a specific token (string or character) has been reached?

One VIM-compatible way to do this could be to allow `:JsonPath` to be used with visual selections as well as given start+end offsets, upon which it would only parse the selected text. That way you could write your own command which located the end of the preamble and fed the rest of the file to jsonpath. Does that sound reasonable?

**Comment by rwmitchell** [comment]
You have understood correctly.

I'd prefer a solution I could configure once.  Writing a vim command could be construed as that, but my vim writing skills are embarrassingly limited.

Unless this could solve a problem for others or is extremely simple, it isn't worth much effort.

I had initially toyed with the idea of having freeform notes with embedded data that could be extracted running the notes as a script.  It works but have ultimately only used it in a few cases.

**Comment by mogelbrod** [comment]
If I were to add support for visual selections you would also be able to select the JSON, enter `:JsonPath ` upon which it would only parse the selected text. You could then create a regular vim binding to run it (using `noremap` or similar).

The reason why I'm suggesting this is because
1. Preambles will likely look very different across filetypes/user/application setups
2. VIM already provides many different ways of navigating/selecting parts of text
3. The option would likely have to be a regular expression to be usable
4. `JsonPath` support for visual selections would solve this request, as well as allowing one-off parsing of embedded JSON in any kind of file

**Comment by mogelbrod** [comment]
I added range support for the command in [v0.4.0](https://github.com/mogelbrod/vim-jsonpath/releases/tag/v0.4.0). If you don't wish to add a custom function/mapping you could manually prefix the function call with the line on which the JSON starts (in your example line 16):
```
:16JsonPath ...
```

**Comment by mogelbrod** [comment]
Closing since the use case should be satisfiable with the addition in v0.4.0.
